### ISSUE TITLE
Connect to Schema

### ISSUE THREAD

**Issue by khattakdev** [eKhattak/hackshare#6]
- [x] Design Database
- [x] Connect To Database
- [x] Create Schemas

![Database (2)](https://user-images.githubusercontent.com/37709578/87334483-28c4c700-c558-11ea-8295-6e7cc6e52a65.png)

**Comment by eKhattak** [comment]
@anshulrgoyal @RashikaKarki @Drewbi  Please share your thoughts on DB Design.

What if we connect Meeting with Learning and auto-create a record for a user when he sends an invitation to an expert?
