### ISSUE TITLE
UI Wireframing

### ISSUE THREAD

**Issue by RashikaKarki** [eKhattak/hackshare#7]
Make a draft UI wireframe for the project
- [x] Landing Page
- [x] Profile Edit Page
- [x] Profile Page
- [x] Find Experts Page

**Comment by RashikaKarki** [comment]
## Landing Page 1
![image](https://user-images.githubusercontent.com/41114269/87308688-4d5e7600-c53b-11ea-9cec-cd5ee5154d8b.png)
## Landing Page 2
![image](https://user-images.githubusercontent.com/41114269/87309138-e8efe680-c53b-11ea-8591-eeb7efb78757.png)
## Profile Page 1
![image](https://user-images.githubusercontent.com/41114269/87309195-fb6a2000-c53b-11ea-83d4-75c7dd79e580.png)
## Profile Page 2
![image](https://user-images.githubusercontent.com/41114269/87309218-0624b500-c53c-11ea-8698-5267b1bfd133.png)
## Profile Page 3
![image](https://user-images.githubusercontent.com/41114269/87309261-12a90d80-c53c-11ea-887a-857d4e768fdf.png)
## Find Expert Page (Option1)- 1
![image](https://user-images.githubusercontent.com/41114269/87309361-353b2680-c53c-11ea-9662-f949abd7be4d.png)
## Find Expert Page (Option 2)-1
![image](https://user-images.githubusercontent.com/41114269/87309404-4a17ba00-c53c-11ea-9ce2-c76e3f4a3cbd.png)
## Find Expert Page - 2
![image](https://user-images.githubusercontent.com/41114269/87309446-5734a900-c53c-11ea-8811-a159cba3b2f1.png)

**Comment by RashikaKarki** [comment]
I am anticipating **Find Learners** page will be pretty similar to **Find Experts** page.
@Drewbi
I am a bit stuck on the Profile editing page. Any suggestions for it?
@anshulrgoyal @eKhattak 
Should we go with Option 1 or Option 2 for **Find Expert Page**? Also let me know if their is anything that I can change.

**Comment by eKhattak** [comment]
> I am anticipating **Find Learners** page will be pretty similar to **Find Experts** page.
> @Drewbi
> I am a bit stuck on the Profile editing page. Any suggestions for it?
> @anshulrgoyal @eKhattak
> Should we go with Option 1 or Option 2 for **Find Expert Page**? Also let me know if their is anything that I can change.

What are the options?

**Comment by khattakdev** [comment]
> I am anticipating **Find Learners** page will be pretty similar to **Find Experts** page.
> @Drewbi
> I am a bit stuck on the Profile editing page. Any suggestions for it?
> @anshulrgoyal @eKhattak
> Should we go with Option 1 or Option 2 for **Find Expert Page**? Also let me know if their is anything that I can change.

I like Option 1 more. Option 2 has a slider for all the languages and for that, we have to manually add all the languages

**Comment by RashikaKarki** [comment]
Any suggestions to improve option 2?
May be we can have "Filter by Skill" option there as well.

**Comment by khattakdev** [comment]
> Any suggestions to improve option 2?
> May be we can have "Filter by Skill" option there as well.

Add Input Search rather than the slider, so the user can manually enter a language. 
For options 2, by default, we can show the list based on the number of endorsements.

**Comment by Drewbi** [comment]
@eKhattak you wouldn't really have to add all the options manually, it would actually be the same approach in option 1 and 2

**Comment by Drewbi** [comment]
I was thinking about the person vs offering list and I realised a great way to do it would be how fiverr does it [example](https://www.fiverr.com/categories/graphics-design/creative-logo-design) 

A person offers something that is different than just "JavaScript" it could be a title which makes it a little more specific such as "teaching canvas and JavaScript".
This way offerings will be easier to take action and choose specific people instead of just whoever has the most endorsements in each category.

**Comment by RashikaKarki** [comment]
> I was thinking about the person vs offering list and I realized a great way to do it would be how Fiverr does it [example](https://www.fiverr.com/categories/graphics-design/creative-logo-design)

@Drewbi  Just like in Fiverr where users can choose different logo styles, formats, here they can select multiple skills?

**Comment by Drewbi** [comment]
@RashikaKarki more along the lines that even though a freelancer might be doing graphic design, they have their listing as "I will create a fun children's illustration" or "I will design your wedding invites".

So the comparison here would be even though two people are listing JavaScript training one could put their title as "I will teach you svg animation with JavaScript"

**Comment by RashikaKarki** [comment]
Gotcha!! Yeah we can do that.

**Comment by khattakdev** [comment]
@Drewbi That's a great idea. It will make those coaching sessions more specific.
